// <auto-generated />
using System;
using BitcoinPayments.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BitcoinPayments.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260314181414_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("payments")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BitcoinPayments.Domain.Entities.Escrow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BuyerChangeIndex")
                        .HasColumnType("integer")
                        .HasColumnName("buyer_change_index");

                    b.Property<int>("BuyerKeyIndex")
                        .HasColumnType("integer")
                        .HasColumnName("buyer_key_index");

                    b.Property<string>("BuyerPublicKeyHex")
                        .IsRequired()
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)")
                        .HasColumnName("buyer_pubkey_hex");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EscrowAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("escrow_address");

                    b.Property<long?>("ExpiresAtBlock")
                        .HasColumnType("bigint")
                        .HasColumnName("expires_at_block");

                    b.Property<Guid?>("FundingUtxoId")
                        .HasColumnType("uuid")
                        .HasColumnName("funding_utxo_id");

                    b.Property<int>("MerchantKeyIndex")
                        .HasColumnType("integer")
                        .HasColumnName("merchant_key_index");

                    b.Property<string>("MerchantPublicKeyHex")
                        .IsRequired()
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)")
                        .HasColumnName("merchant_pubkey_hex");

                    b.Property<Guid>("PaymentTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_transaction_id");

                    b.Property<string>("RedeemScriptHex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("redeem_script_hex");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("state");

                    b.Property<int>("TimelockBlocks")
                        .HasColumnType("integer")
                        .HasColumnName("timelock_blocks");

                    b.Property<string>("TimelockRefundTransactionHex")
                        .HasColumnType("text")
                        .HasColumnName("timelock_refund_tx_hex");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("escrows", "payments");
                });

            modelBuilder.Entity("BitcoinPayments.Domain.Entities.IdempotencyKeyRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response_body");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.HasKey("Key");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_idempotency_expires");

                    b.ToTable("idempotency_keys", "payments");
                });

            modelBuilder.Entity("BitcoinPayments.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_satoshis");

                    b.Property<string>("BitcoinTxId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("bitcoin_tx_id");

                    b.Property<Guid>("BuyerWalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_wallet_id");

                    b.Property<int>("ConfirmationCount")
                        .HasColumnType("integer")
                        .HasColumnName("confirmation_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<long?>("Fee")
                        .HasColumnType("bigint")
                        .HasColumnName("fee_satoshis");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("MerchantWalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_wallet_id");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("operation_type");

                    b.Property<Guid?>("ParentTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_transaction_id");

                    b.Property<string>("RawTransactionHex")
                        .HasColumnType("text")
                        .HasColumnName("raw_transaction_hex");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BitcoinTxId")
                        .HasDatabaseName("idx_payment_tx_bitcoin_txid");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ParentTransactionId")
                        .HasDatabaseName("idx_payment_tx_parent");

                    b.HasIndex("State")
                        .HasDatabaseName("idx_payment_tx_state");

                    b.ToTable("payment_transactions", "payments");
                });

            modelBuilder.Entity("BitcoinPayments.Domain.Entities.Utxo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("address");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_satoshis");

                    b.Property<int>("ConfirmationCount")
                        .HasColumnType("integer")
                        .HasColumnName("confirmation_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DerivationIndex")
                        .HasColumnType("integer")
                        .HasColumnName("derivation_index");

                    b.Property<bool>("IsChangeAddress")
                        .HasColumnType("boolean")
                        .HasColumnName("is_change_address");

                    b.Property<bool>("IsEscrow")
                        .HasColumnType("boolean")
                        .HasColumnName("is_escrow");

                    b.Property<bool>("IsSpent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_spent");

                    b.Property<int>("OutputIndex")
                        .HasColumnType("integer")
                        .HasColumnName("output_index");

                    b.Property<string>("ScriptPubKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("script_pubkey");

                    b.Property<string>("SpentByTx")
                        .HasColumnType("text")
                        .HasColumnName("spent_by_tx");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("transaction_id");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId", "OutputIndex")
                        .IsUnique();

                    b.HasIndex("WalletId", "IsSpent")
                        .HasDatabaseName("idx_utxos_wallet_unspent");

                    b.ToTable("utxos", "payments");
                });

            modelBuilder.Entity("BitcoinPayments.Domain.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentChangeIndex")
                        .HasColumnType("integer")
                        .HasColumnName("current_change_index");

                    b.Property<int>("CurrentReceivingIndex")
                        .HasColumnType("integer")
                        .HasColumnName("current_receiving_index");

                    b.Property<string>("EncryptedMasterKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_master_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("network");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("wallets", "payments");
                });
#pragma warning restore 612, 618
        }
    }
}
